@echo off
cmake . -Bbin -G"Visual Studio 16 2019"
MSBuild.exe bin/Dragon.sln -m
copy "bin\Debug\OpenWindow.exe"		 				"binary_out\OpenWindow.exe"
copy "bin\Debug\OpenWindow.pdb" 					"binary_out\OpenWindow.pdb"
copy "bin\src\Debug\Dragon.dll" 					"binary_out\Dragon.dll"
copy "bin\src\Debug\Dragon.lib" 					"binary_out\Dragon.lib"
copy "bin\src\Debug\Dragon.exp" 					"binary_out\Dragon.exp"
copy "bin\src\Debug\Dragon.pdb" 					"binary_out\Dragon.pdb"
copy "bin\lib\glfw\src\Debug\glfw.lib" 				"binary_out\glfw.lib"
copy "bin\lib\glfw\src\Debug\glfw.pdb"				"binary_out\glfw.pdb"
copy "bin\lib\OpenAL-Soft\Debug\alrecord.exe"		"binary_out\alrecord.exe"
copy "bin\lib\OpenAL-Soft\Debug\alrecord.pdb"		"binary_out\alrecord.pdb"
copy "bin\lib\OpenAL-Soft\Debug\altonegen.exe"		"binary_out\altonegen.exe"
copy "bin\lib\OpenAL-Soft\Debug\altonegen.pdb"		"binary_out\altonegen.pdb"
copy "bin\lib\OpenAL-Soft\Debug\common.lib"			"binary_out\common.lib"
copy "bin\lib\OpenAL-Soft\Debug\common.pdb"			"binary_out\common.pdb"
copy "bin\lib\OpenAL-Soft\Debug\ex-common.lib"		"binary_out\ex-common.lib"
copy "bin\lib\OpenAL-Soft\Debug\ex-common.pdb"		"binary_out\ex-common.pdb"
copy "bin\lib\OpenAL-Soft\Debug\openal-info.exe"	"binary_out\openal-info.exe"
copy "bin\lib\OpenAL-Soft\Debug\openal-info.pdb"	"binary_out\openal-info.pdb"
copy "bin\lib\OpenAL-Soft\Debug\OpenAL32.dll"		"binary_out\OpenAL32.dll"
copy "bin\lib\OpenAL-Soft\Debug\OpenAL32.exp"		"binary_out\OpenAL32.exp"
copy "bin\lib\OpenAL-Soft\Debug\OpenAL32.lib"		"binary_out\OpenAL32.lib"
copy "bin\lib\OpenAL-Soft\Debug\OpenAL32.pdb"		"binary_out\OpenAL32.pdb"