cmake_minimum_required(VERSION 3.20)

set(Dragon_INSTALL_DEST ${Dragon_VERSION}/${CMAKE_BUILD_TYPE})

install(TARGETS ${Dragon_LIB_NAME} DESTINATION ${Dragon_VERSION}/${CMAKE_BUILD_TYPE}/bin)
install(DIRECTORY ${Dragon_SOURCE_DIR}/include/dragon DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
