install(TARGETS ${Dragon_LIB_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})
install(DIRECTORY ${Dragon_SOURCE_DIR}/include/dragon DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
install(DIRECTORY ${Dragon_BINARY_DIR}/src/shaders DESTINATION ${CMAKE_INSTALL_LIBDIR} FILES_MATCHING PATTERN "*.spv")