name: Get Dragon Dependencies
author: KhrySystem
description: Gets and installs dependencies to build Dragon


runs: 
  using: 'composite'

  steps:
    - run: |
        if [[ $RUNNER_OS == 'Linux' ]]; then
          sudo apt install build-essential cmake libgl1-mesa-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxxf86vm-dev mesa-common-dev
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          sudo apt install -qq libpulse-dev portaudio19-dev libasound2-dev libjack-dev libpipewire-0.3-dev qtbase5-dev libdbus-1-dev
        fi
      shell: bash

    - name: Install Vulkan
      id: install-vulkan
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with: 
        version: latest
        cache: true
        quiet: false