name: Get Dragon Dependencies
author: KhrySystem
description: Gets and installs dependencies to build Dragon

inputs:
  cmake-generator:
    required: true
  boost-toolset:
    required: true
  platform-version:
    required: true

runs: 
  using: 'composite'

  steps:
    - run: |
        if [[ $RUNNER_OS == 'Linux' ]]; then
          sudo apt install build-essential cmake libgl1-mesa-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxxf86vm-dev mesa-common-dev
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
        fi
      shell: bash

    - name: Install Boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.0
      with:
        boost_version: 1.79.0
        platform_version: ${{inputs.platform-version}}
        toolset: ${{inputs.boost-toolset}}

    - name: Install OpenCL
      uses: KhrySystem/install-opencl@main
      with: 
        version: v2022.09.30
        cache: true
        cmake_args: '-G"${{inputs.cmake-generator}}"'
        path: opencl

    - name: Install Vulkan
      id: install-vulkan
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with: 
        version: latest
        cache: true
        quiet: false