name: Linux Build

on: 
  push:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**/.gitignore'

  pull_request_review:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**/.gitignore'

jobs:
  build-linux:
    name: Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04 ]
        type: [ BUILD_SHARED_LIBS=OFF, BUILD_SHARED_LIBS=ON ]
        cfg: [ Debug, Release ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install APT dependencies for GLFW
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: latest 
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-use-cache: true

      - name: Update Git Subdirectories
        run: |
          git submodule update --init

      - name: Build Dragon
        run: |
            cmake . -B build  -D${{ matrix.type }}  -DCMAKE_INSTALL_DIR=${{ github.workspace }}/install -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
            cmake --build ${{ github.workspace }}/build --config ${{ matrix.cfg }}
            cmake --install ${{ github.workspace }}/build
