name: Dragon Build
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        config: [ Debug, Release ]
        shared: [ "ON", "OFF" ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install APT dependencies for GLFW
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libext-dev

      - name: Update Git Subdirectories
        run: |
          git submodule update --init

      - name: Build Dragon
        run: |
          cmake . -B build -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build ${{github.workspace}}/build


  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]
        shared: [ "ON", "OFF" ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install APT dependencies for GLFW
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libext-dev

      - name: Update Git Subdirectories
        run: |
          git submodule update --init

      - name: Get Vulkan
        uses: humbletim/install-vulkan-sdk@v1.1.1

      - name: Build Dragon
        run: |
          cmake . -B build -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build ${{github.workspace}}/build