name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-linux-unix-makefiles:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: | 
            sudo add-apt-repository ppa:oibaf/graphics-drivers
            sudo apt update
            sudo apt upgrade
            sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils
            
            wget --referer http://support.amd.com https://drivers.amd.com/drivers/linux/amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz
            
            tar -Jxvf amdgpu-pro-20.45-1188099-ubuntu-20.04.tar.xz
            cd amdgpu-pro-20.45-1188099-ubuntu-20.04
            ./amdgpu-pro-install --opencl=pal
            cd ..
            
            wget https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0_rc1.tar.gz
            
            tar --bzip2 -xf boost_1_80_0_rc1.tar.gz
            cd boost_1_80_0_rc1
            ./booststrap.sh
            
            sudo ./b2 install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/bin -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDRAGON_INSTALL_DIR:String="${{github.workspace}}/sdk_build"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
