name: Dragon Build
on: [push, pull_request]

jobs:
  build-linux:
    name: Linux
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        type: [ BUILD_SHARED_LIBS=ON, BUILD_SHARED_LIBS=OFF ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install APT dependencies for GLFW
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

      - name: Install Vulkan
        run: |
          sudo apt install libvulkan1 libvulkan-dev mesa-vulkan-drivers vulkan-utils

      - name: Update Git Subdirectories
        run: |
          git submodule update --init

      - name: Build Dragon
        run: |
          cmake . -B build -D${{ matrix.type }} -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{github.workspace}}/build

      - name: Test Dragon
        run: |
          cd ${{github.workspace}}/build
          ctest -W --output-on-failure --parallel 2


  build-windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      matrix:
        type: [ BUILD_SHARED_LIBS=ON, BUILD_SHARED_LIBS=OFF ]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Git Subdirectories
        run: |
          git submodule update --init

      - name: Install Vulkan
        uses: humbletim/install-vulkan-sdk@v1.1.1

      - name: Build Dragon
        run: |
          cmake . -B build -D${{ matrix.type }} -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{github.workspace}}/build

      - name: Test Dragon
        run: |
          cd ${{github.workspace}}/build
          ctest -W --output-on-failure --parallel 2