name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-linux-unix-makefiles:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: | 
            sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils
            
            wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12260.1/intel-igc-core_1.0.12260.1_amd64.deb
            wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.12260.1/intel-igc-opencl_1.0.12260.1_amd64.deb
            wget https://github.com/intel/compute-runtime/releases/download/latest/intel-level-zero-gpu-dbgsym_1.3.24420_amd64.ddeb
            wget https://github.com/intel/compute-runtime/releases/download/latest/intel-level-zero-gpu_1.3.24420_amd64.deb
            wget https://github.com/intel/compute-runtime/releases/download/latest/intel-opencl-icd-dbgsym_22.41.24420_amd64.ddeb
            wget https://github.com/intel/compute-runtime/releases/download/latest/intel-opencl-icd_22.41.24420_amd64.deb
            wget https://github.com/intel/compute-runtime/releases/download/latest/libigdgmm12_22.2.0_amd64.deb
            
            sudo dpkg -i *.deb

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/bin -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDRAGON_INSTALL_DIR:String="${{github.workspace}}/sdk_build"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
